name: "Cargo update"
on:
  schedule:
    - cron: "0 5 * * 1" # Runs at 05:00, only on Monday

jobs:
  cargo-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Update swc_core
        uses: VKCOM/gh-actions/shared/rust/cargo-update-toml@main
        with:
          packages: swc_core
      - uses: VKCOM/gh-actions/shared/rust/cargo-update-pr@main
        with:
          token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}
