on:
  workflow_call:
    inputs:
      ref:
        description: "The branch, tag or SHA to checkout"
        default: ${{ github.ref }}
        required: false
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      # - uses: VKCOM/gh-actions/shared/rust/cargo-cache@main

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      # - uses: VKCOM/gh-actions/shared/rust/cargo-cache@main
      - name: Install cargo-llvm-cov
        run: curl --proto '=https' --tlsv1.2 -fsSL "https://github.com/taiki-e/cargo-llvm-cov/releases/download/v0.6.16/cargo-llvm-cov-$(rustc -vV | grep '^host:' | cut -d' ' -f2).tar.gz"  | tar xzf - -C "$HOME/.cargo/bin"

      - name: Generate code coverage
        run: cargo llvm-cov --all-features --lcov --branch --output-path lcov.info

      - name: Upload test artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: |
            lcov.info

  deploy_test_coverage:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download test artifact
        uses: actions/download-artifact@v4
        with:
          name: test-output

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          files: lcov.info
          fail_ci_if_error: true
          verbose: true

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      # - uses: VKCOM/gh-actions/shared/rust/cargo-cache@main

      - name: Run Build
        run: cargo build-wasip1 --release
